In [3]:
from sqlalchemy import create_engine, MetaData,Table, Column, Integer, String, ForeignKey, DateTime, Date, Time, Numeric, Text, insert, Float, Enum, case
from sqlalchemy.orm import declarative_base, relationship

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
# les saisons : 
dataframe_saisons = pd.read_csv('../data/Brose/data_saison.csv')
dataframe_saisons.head(3)

   id_saison     Annees
0          1  2024-2025

In [5]:
# les competitions : 
dataframe_competitions = pd.read_csv('../data/Brose/data_competitions.csv')
dataframe_competitions.head(3)

   id_competition nom_competition
0               1  Premier League
1               2    Champions Lg
2               3         EFL Cup

In [6]:
# les equipes : 
dataframe_equipe = pd.read_csv('../data/Brose/data_equipes.csv')
dataframe_equipe.head(3)

   id_equipe           Equipe  id_saison
0          1    AFC Wimbledon          1
1          2  Acc'ton Stanley          1
2          3          Arsenal          1

In [7]:
# les matches : 
dataframe_matche = pd.read_csv('../data/Brose/data_matches.csv')
dataframe_matche.head(3)

,id_match,date_match,heure,round,venue,id_team_home,id_team_away,id_competition,id_saison
0,1,2024-08-17,12:30,Matchweek 1,Away,30,27,1,1
1,2,2024-08-25,16:30,Matchweek 2,Home,30,11,1,1
2,3,2024-09-01,16:00,Matchweek 3,Away,30,33,1,1

In [8]:
# les players : 
dataframe_player = pd.read_csv('../data/Brose/data_players.csv')
dataframe_player.head(3)

   id_joueur        nom_joueur position nationalite  id_equipe
0          1     Mohamed Salah       FW      eg EGY         30
1          2   Virgil van Dijk       DF      nl NED         30
2          3  Ryan Gravenberch       MF      nl NED         30

In [9]:
# les resultats : 
dataframe_resultat = pd.read_csv('../data/Brose/data_resultat_match.csv')
dataframe_resultat.head(3)

   id_resultat  id_match  id_equipe  buts_marques  buts_concedes  resultat
0            1         1         30             2              0  Victoire
1            2         1         27             0              2   Défaite
2            3         2         30             2              0  Victoire

In [10]:
dataframe_statistique = pd.read_csv('../data/Brose/statistiques_joueurs.csv')
dataframe_statistique.head(3)

   id_joueur       nom_joueur position nationalite  id_equipe
0        133  Aaron Anselmino       DF      ar ARG         18
1        462  Aaron Cresswell       DF     eng ENG         55
2        341     Aaron Hickey    DF,MF     sct SCO         11

In [11]:
dataframe_statistique.isnull().sum()

id_joueur      0
nom_joueur     0
position       0
nationalite    0
id_equipe      0
dtype: int64

In [12]:

Base = declarative_base()
metadata = MetaData()
engine = create_engine("postgresql://postgres:bouchra@localhost:5432/pr_db")

In [13]:
Saison = Table(
    'saisons', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("annees", String, unique=True, index=True, nullable=False)
)

In [14]:

Competition = Table(
    'competitions', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("nom_competition", String, unique=True, index=True, nullable=False)
)

In [15]:
Equipe = Table(
    'equipes', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("equipe", String, index=True, nullable=False),
    Column("saison_id", Integer, ForeignKey("saisons.id", ondelete="CASCADE"))
)

In [16]:

Joueur = Table(
    'joueurs', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("nom_joueur", String, index=True, nullable=False),
    Column("position", String, index=True, nullable=False),
    Column("nationalite", String, index=True, nullable=False),
    Column("equipe_id", Integer, ForeignKey("equipes.id", ondelete="CASCADE"))
)

In [17]:
Matche = Table(
    'matches', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("date_match", Date, nullable=False),
    Column("heure", Time, nullable=False),
    Column("round", String, index=True, nullable=False),
    Column("venue", Enum('Home', 'Away', 'Neutral', name='venue_enum'), nullable=False),
    Column("team_home_id", Integer, ForeignKey("equipes.id", ondelete="CASCADE")),
    Column("team_away_id", Integer, ForeignKey("equipes.id", ondelete="CASCADE")),
    Column("competition_id", Integer, ForeignKey("competitions.id", ondelete="CASCADE")),
    Column("saison_id", Integer, ForeignKey("saisons.id", ondelete="CASCADE")),
)

In [18]:

Resultat_Match = Table(
    'resultat_matchs', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("matche_id", Integer, ForeignKey("matches.id", ondelete="CASCADE")),
    Column("equipe_id", Integer, ForeignKey("equipes.id", ondelete="CASCADE")),
    Column("buts_marques", Integer, nullable=False),
    Column("buts_concedes", Integer, nullable=False),
    Column("resultat", Enum('Victoire', 'Défaite', 'Nul', name='resultat_enum'), nullable=False),
)

In [19]:

Stat_joueur = Table(
    'statistiques_joueurs', metadata,
    Column("id", Integer, primary_key=True, index=True),
    Column("joueur_id", Integer, ForeignKey("joueurs.id", ondelete="CASCADE")),
    Column("buts", Float, nullable=False),  
    Column("passes_decisives", Float, nullable=False),  
    Column("nb_matches_played", Integer, nullable=False),
    Column("cartons_jaunes", Float, nullable=False),  
    Column("cartons_rouges", Float, nullable=False),  
)

In [20]:

try:
    connection = engine.connect()
    
    transaction = connection.begin()
    metadata.drop_all(bind=connection) 
    metadata.create_all(bind=connection) 
    print("Tables créées avec succès !")
    
    transaction.commit()
    connection.close()
except Exception as ex:
    print("Erreur :", ex)

Tables créées avec succès !

In [22]:
try:
        connection = engine.connect()
        transaction = connection.begin()
        
        data_mapping = {
            Saison: dataframe_saisons.rename(columns={'id_saison': 'id', 'Annees': 'annees'}),
            Competition: dataframe_competitions.rename(columns={'id_competition': 'id', 'nom_competition': 'nom_competition'}),
            Equipe: dataframe_equipe.rename(columns={'id_equipe': 'id', 'Equipe': 'equipe', 'id_saison': 'saison_id'}),
            Joueur: dataframe_player.rename(columns={'id_joueur': 'id', 'nom_joueur': 'nom_joueur', 'position': 'position', 
                                                   'nationalite': 'nationalite', 'id_equipe': 'equipe_id'}),
            Matche: dataframe_matche.rename(columns={'id_match': 'id', 'date_match': 'date_match', 'heure': 'heure',
                                                   'round': 'round', 'venue': 'venue', 'id_team_home': 'team_home_id',
                                                   'id_team_away': 'team_away_id', 'id_competition': 'competition_id',
                                                   'id_saison': 'saison_id'}),
            Resultat_Match: dataframe_resultat.rename(columns={'id_resultat': 'id', 'id_match': 'matche_id', 
                                                             'id_equipe': 'equipe_id', 'buts_marques': 'buts_marques',
                                                             'buts_concedes': 'buts_concedes', 'resultat': 'resultat'}),
            Stat_joueur: dataframe_statistique.rename(columns={'id_stats': 'id', 'id_joueur': 'joueur_id', 'buts': 'buts',
                                                             'passes_decisives': 'passes_decisives', 
                                                             'nb_matches_played': 'nb_matches_played',
                                                             'cartons_jaunes': 'cartons_jaunes', 
                                                             'cartons_rouges': 'cartons_rouges'})
        }
        

        insertion_order = [Saison, Competition, Equipe, Joueur, Matche, Resultat_Match, Stat_joueur]
        
        for table in insertion_order:
            df = data_mapping[table]
            print(f"Insertion dans {table.name} : {len(df)} lignes")
            
            data_to_insert = df.to_dict('records')
            
            if data_to_insert:
                connection.execute(insert(table), data_to_insert)
        
        transaction.commit()
        connection.close()
        print("Données insérées avec succès !")
        
except Exception as ex:
        transaction.rollback()
        print("Erreur lors de l'insertion des données :", ex)
        raise

Insertion dans saisons : 1 lignes
Insertion dans competitions : 7 lignes
Insertion dans equipes : 113 lignes
Insertion dans joueurs : 702 lignes
Insertion dans matches : 559 lignes
Insertion dans resultat_matchs : 1118 lignes
Insertion dans statistiques_joueurs : 702 lignes
Erreur lors de l'insertion des données : (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « buts » dans la relation « statistiques_joueurs »
DETAIL:  La ligne en échec contient (2, 133, null, null, null, null, null).

[SQL: INSERT INTO statistiques_joueurs (joueur_id) VALUES (%(joueur_id__0)s), (%(joueur_id__1)s), (%(joueur_id__2)s), (%(joueur_id__3)s), (%(joueur_id__4)s), (%(joueur_id__5)s), (%(joueur_id__6)s), (%(joueur_id__7)s), (%(joueur_id__8)s), (%(joueur_id__9)s) ... 15034 characters truncated ... r_id__697)s), (%(joueur_id__698)s), (%(joueur_id__699)s), (%(joueur_id__700)s), (%(joueur_id__701)s)]
[parameters: {'joueur_id__0': 133, 'joueur_id__1': 462, 'joueur_id__2': 341, 'joueur_id__3': 668, 'joueur_id__4': 66, 'joueur_id__5': 446, 'joueur_id__6': 414, 'joueur_id__7': 90, 'joueur_id__8': 613, 'joueur_id__9': 678, 'joueur_id__10': 686, 'joueur_id__11': 284, 'joueur_id__12': 245, 'joueur_id__13': 384, 'joueur_id__14': 356, 'joueur_id__15': 693, 'joueur_id__16': 479, 'joueur_id__17': 347, 'joueur_id__18': 685, 'joueur_id__19': 164, 'joueur_id__20': 642, 'joueur_id__21': 287, 'joueur_id__22': 141, 'joueur_id__23': 4, 'joueur_id__24': 585, 'joueur_id__25': 581, 'joueur_id__26': 545, 'joueur_id__27': 590, 'joueur_id__28': 659, 'joueur_id__29': 8, 'joueur_id__30': 452, 'joueur_id__31': 494, 'joueur_id__32': 482, 'joueur_id__33': 179, 'joueur_id__34': 28, 'joueur_id__35': 354, 'joueur_id__36': 229, 'joueur_id__37': 7, 'joueur_id__38': 518, 'joueur_id__39': 475, 'joueur_id__40': 188, 'joueur_id__41': 467, 'joueur_id__42': 210, 'joueur_id__43': 148, 'joueur_id__44': 273, 'joueur_id__45': 346, 'joueur_id__46': 503, 'joueur_id__47': 574, 'joueur_id__48': 563, 'joueur_id__49': 305 ... 602 parameters truncated ... 'joueur_id__652': 375, 'joueur_id__653': 127, 'joueur_id__654': 182, 'joueur_id__655': 143, 'joueur_id__656': 262, 'joueur_id__657': 595, 'joueur_id__658': 493, 'joueur_id__659': 2, 'joueur_id__660': 411, 'joueur_id__661': 318, 'joueur_id__662': 23, 'joueur_id__663': 97, 'joueur_id__664': 460, 'joueur_id__665': 21, 'joueur_id__666': 227, 'joueur_id__667': 684, 'joueur_id__668': 646, 'joueur_id__669': 472, 'joueur_id__670': 116, 'joueur_id__671': 551, 'joueur_id__672': 596, 'joueur_id__673': 622, 'joueur_id__674': 304, 'joueur_id__675': 382, 'joueur_id__676': 582, 'joueur_id__677': 161, 'joueur_id__678': 31, 'joueur_id__679': 683, 'joueur_id__680': 365, 'joueur_id__681': 223, 'joueur_id__682': 571, 'joueur_id__683': 594, 'joueur_id__684': 617, 'joueur_id__685': 588, 'joueur_id__686': 240, 'joueur_id__687': 238, 'joueur_id__688': 322, 'joueur_id__689': 535, 'joueur_id__690': 314, 'joueur_id__691': 171, 'joueur_id__692': 434, 'joueur_id__693': 677, 'joueur_id__694': 332, 'joueur_id__695': 565, 'joueur_id__696': 226, 'joueur_id__697': 405, 'joueur_id__698': 300, 'joueur_id__699': 215, 'joueur_id__700': 73, 'joueur_id__701': 458}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

IntegrityError: (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « buts » dans la relation « statistiques_joueurs »
DETAIL:  La ligne en échec contient (2, 133, null, null, null, null, null).

[SQL: INSERT INTO statistiques_joueurs (joueur_id) VALUES (%(joueur_id__0)s), (%(joueur_id__1)s), (%(joueur_id__2)s), (%(joueur_id__3)s), (%(joueur_id__4)s), (%(joueur_id__5)s), (%(joueur_id__6)s), (%(joueur_id__7)s), (%(joueur_id__8)s), (%(joueur_id__9)s) ... 15034 characters truncated ... r_id__697)s), (%(joueur_id__698)s), (%(joueur_id__699)s), (%(joueur_id__700)s), (%(joueur_id__701)s)]
[parameters: {'joueur_id__0': 133, 'joueur_id__1': 462, 'joueur_id__2': 341, 'joueur_id__3': 668, 'joueur_id__4': 66, 'joueur_id__5': 446, 'joueur_id__6': 414, 'joueur_id__7': 90, 'joueur_id__8': 613, 'joueur_id__9': 678, 'joueur_id__10': 686, 'joueur_id__11': 284, 'joueur_id__12': 245, 'joueur_id__13': 384, 'joueur_id__14': 356, 'joueur_id__15': 693, 'joueur_id__16': 479, 'joueur_id__17': 347, 'joueur_id__18': 685, 'joueur_id__19': 164, 'joueur_id__20': 642, 'joueur_id__21': 287, 'joueur_id__22': 141, 'joueur_id__23': 4, 'joueur_id__24': 585, 'joueur_id__25': 581, 'joueur_id__26': 545, 'joueur_id__27': 590, 'joueur_id__28': 659, 'joueur_id__29': 8, 'joueur_id__30': 452, 'joueur_id__31': 494, 'joueur_id__32': 482, 'joueur_id__33': 179, 'joueur_id__34': 28, 'joueur_id__35': 354, 'joueur_id__36': 229, 'joueur_id__37': 7, 'joueur_id__38': 518, 'joueur_id__39': 475, 'joueur_id__40': 188, 'joueur_id__41': 467, 'joueur_id__42': 210, 'joueur_id__43': 148, 'joueur_id__44': 273, 'joueur_id__45': 346, 'joueur_id__46': 503, 'joueur_id__47': 574, 'joueur_id__48': 563, 'joueur_id__49': 305 ... 602 parameters truncated ... 'joueur_id__652': 375, 'joueur_id__653': 127, 'joueur_id__654': 182, 'joueur_id__655': 143, 'joueur_id__656': 262, 'joueur_id__657': 595, 'joueur_id__658': 493, 'joueur_id__659': 2, 'joueur_id__660': 411, 'joueur_id__661': 318, 'joueur_id__662': 23, 'joueur_id__663': 97, 'joueur_id__664': 460, 'joueur_id__665': 21, 'joueur_id__666': 227, 'joueur_id__667': 684, 'joueur_id__668': 646, 'joueur_id__669': 472, 'joueur_id__670': 116, 'joueur_id__671': 551, 'joueur_id__672': 596, 'joueur_id__673': 622, 'joueur_id__674': 304, 'joueur_id__675': 382, 'joueur_id__676': 582, 'joueur_id__677': 161, 'joueur_id__678': 31, 'joueur_id__679': 683, 'joueur_id__680': 365, 'joueur_id__681': 223, 'joueur_id__682': 571, 'joueur_id__683': 594, 'joueur_id__684': 617, 'joueur_id__685': 588, 'joueur_id__686': 240, 'joueur_id__687': 238, 'joueur_id__688': 322, 'joueur_id__689': 535, 'joueur_id__690': 314, 'joueur_id__691': 171, 'joueur_id__692': 434, 'joueur_id__693': 677, 'joueur_id__694': 332, 'joueur_id__695': 565, 'joueur_id__696': 226, 'joueur_id__697': 405, 'joueur_id__698': 300, 'joueur_id__699': 215, 'joueur_id__700': 73, 'joueur_id__701': 458}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)